### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [alexmoiseyenko/my-telegram#1]
Thanks for efforts, looks quite good in general. A few notes
![image](https://user-images.githubusercontent.com/5592397/92306485-0b303e80-ef98-11ea-9f51-5dfad1ad6b23.png)

**Comment by alexmoiseyenko** [comment]
Thank you for review! I added rows to the needed area and fixed problem with message area.

**Comment by ilya4321** [comment]
Looking good now, thanks!
